packages:
  - packages/*

allowBuilds:
  esbuild: true
  electron: true
  "@google/genai": false
  msgpackr-extract: false
  protobufjs: false

minimumReleaseAgeExclude:
  - electron@44.4.3
  - "@effect/platform-node-shared@4.0.0"
  - "@effect/platform-node@4.0.0"
  - effect@4.0.0

overrides:
  "@effect/platform-node-shared": 4.0.0
