name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
  pull_request:
    paths-ignore:
      - docs/**

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v7.0.1
      - uses: pnpm/action-setup@v6.0.9
        with:
          version: 11.13.0
          run_install: false
      - uses: actions/setup-node@v7.0.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm check
      - run: pnpm build
